//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advisor.WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Advisor.WebAPI.Models;
    
    public partial class AdvisorEntities : DbContext
    {
        public AdvisorEntities()
            : base("name=AdvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ticker> Ticker { get; set; }
        public DbSet<TickerDailyData> TickerDailyData { get; set; }
        public DbSet<TickerMonthlyData> TickerMonthlyData { get; set; }
        public DbSet<TickerWeeklyData> TickerWeeklyData { get; set; }
    }
}
