//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advisor.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickerMonthlyData
    {
        public long ID { get; set; }
        public short TickerID { get; set; }
        public System.DateTime Point { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public long Volume { get; set; }
    
        public virtual Ticker Ticker { get; set; }
    }
}
